name: "Next.js Build Action"
description: "Builds the Next.js project"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "22"
outputs:
  message:
    description: "Build status message"
runs:
  using: "node16"
  main: "dist/index.js" # Change this to point to the bundled file
